# Generated by Django 4.0.3 on 2022-04-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='centrales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=30)),
                ('cant_EC', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fabricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=30)),
                ('empleados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reactores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
